# Sample calibration file

# Noise parameters of sensors (Variances)
noise_std:
  # Accelerometer, units of Gs squared
  accel:
    x: 0.1
    y: 0.1
    z: 0.1
  # Gyroscope, units of rad/s squared
  gyro:
    x: 0.001
    y: 0.001
    z: 0.001
  # Magnetometer, units of Gauss squared
  mag:
    x: 0.1
    y: 0.1
    z: 0.1

# Threshold used to enable bias calculation (rad/s)
gyro_bias_thresh: 0.01
